### ISSUE TITLE
综合性建议

### ISSUE THREAD

**Issue by Executor-Cheng** [DavidSciMeow/MeowMiraiLib#1]
1. 对 `Client` 类的设计问题:
现在你的设计中, `Client` 下的 `ws`, `session`, `SSMRequestList` 字段均为静态。假如用户使用两个(或以上)不同的 `mirai-api-http` 服务器, 第二次初始化 `Client` 实例时将导致 `ws` 字段被覆盖, 连接后将导致 `session` 字段被覆盖, `SSMRequestList` 将包含来自不同主机的消息。请考虑将这三个字段改为实例
2. 对 payload 的构建问题:
现在你是使用字符串拼接来构建 payload 并发送给 `mirai-api-http`, 如果用户给定的参数中未对双引号进行转义, 构建后的 payload 将成为无效的 json。请考虑使用 DOM api 构建json, 或者自己创建泛型类并将其序列化为json。
例子:
```csharp
string payload = $"{{\"syncId\":{syncId},\"command\":\"{command}\"," +
                    $"{(subCommand != null ? $"\"subCommand\":\"{subCommand}\"," : "")}" +
                    $"\"content\":{content}}}";
// 改为:
JObject j = new JObject();
j["syncId"] = syncId;
j["command"] = command;
j["subCommand"] = subCommand;
j["content"] = JToken.FromObject(...);
// 或者做泛型类
public class MiraiWebSocketCommand<T> // 你可以把你自己的SSM类稍微调整一下
{
    [JsonProperty("syncId")]
    public int? SyncId { get; set; }

    [JsonProperty("command")]
    public string Command { get; set; }

    [JsonProperty("subCommand")]
    public string? SubCommand { get; set; }

    [JsonProperty("content")]
    public T Content { get; set; }
}
```
3. `SSMRequestList` 的设计问题:
如果 `syncId` 不可能重复, 请考虑使用 `IDictionary<int, JObject>`, 如果可能重复, 请考虑 `IDictionary<int, ConcurrentQueue<JObject>>`, 使用 `TryGetValue(int, out ?)` 获取用户给定的 `syncId` 所对应的值
4. `Client` 中异步方法设计的问题:
`Task<bool> ConnectAsync()` 方法可用以下表达式避免创建新的状态机:
`public Task<bool> ConnectAsync() => ws.OpenAsync();`
5. `Client.SendAndWaitResponse` 也应改为实例方法, 且其中的 `TimeOut` 参数未使用。
一般 `TimeOut` 会搭配 `CancellationTokenSource` 进行使用, 同步方法中基本上没有接受 `CancellationToken` 的方法, 多考虑使用异步方法
6. 其它的一些选择:
你可以尝试 `System.Net.WebSockets.ClientWebSocket` 还有 `System.Text.Json` 下的 api

**Comment by RoslynMeow** [comment]
对于问题1的解答:
框架需要设置静态标量来控制整个收发分离, 而且我也不建议`一个项目` `同时链接` `两个` api, 
如确有需要你可以建立两个项目分别引用本库.

对于问题2的解答:
首先,所有的序列化均由`Newtonsoft`进行转义,
构建信息的操作是 `dynamic类型`的`Client属性Content`转义, //SSM.cs line 58;
Newtonsoft会自己转义内部的实例并序列化成字符串,
而`syncId`,`command`,`subCommand`是由框架控制的, `除非用户使用反射调取`, 否则按照最小开发原则一切可控.
如果`害怕用户进行错误使用`, 那么在每个SSM的继承类中, 用户只需要 `按照标准` 传入参数即可. 
而如果`非要进行严格的筛查`, `其实只需要改动静态类的生成方案`把父类 `Content赋值的时候填写为this`, 生成类内属性后交由父类序列化即可.
在发送最终文本使用字符串能`减少类设计`这是第一, 而且会节约掉Newtonsoft的`二次静态转义方案`, 
而且, "用户"即使不进行转义, 在newtonsoft转义后Json有效但这个报文无效, 不如直接无效, 而且本问题应该是使用者自己进行决定的.

对于问题3的解答: 首先SyncId如果用户不修改默认是随机的, 而随机的数字是个`long类型的随机数`, 而且仅对于`用户发报回收报文有效`. 而服务器相应给用户的是固定的 -1,所以只需要`保存JObject`后`使用linq查找`即可, 而且框架会自动控制队列内的对比和查找方案, 且 Queue<JObject> 对于`单一服务器`的静态队列是使用 `死 循 环 方案进行筛选` 这样在每一次异步lambda的时候能最快, 最小的查找出最优方案. 而队列仅会在客户端发信后进行入队出队, 在给定时间内, 队列大部分时间总是空的. 从而保证了处理效率和内存最优.
关于队列回查的值, 查看 client.cs SendAndWaitResponse函数 line 74;

对于问题4的异步问题, 异步我还在探索, 而在大多数方式中我个人感觉不必要, 但根据API设计原则, 写上了就不能随便删除, 所以就留下了.

对于问题5的解答,部分参见问题1, TimeOut是第一版设计的冗余, 其原来的作用是根据Timeout设置返回超时判定服务器响应, 而新版API中我使用等待队列进行反馈, 而且SendAndWaitResponse是一个Lambda异步调用方法, 不归属于实例. 
且根据API设计原则, 我觉得以后`可能还有用`, 所以目前暂时保留.

对于问题6的解答, Web4Socket内部兼容socketIO 而这个SocketIO在后续的升级可能用途很大, System.Text.Json个人觉得不如Newtonsoft好用, newtonsoft还能序列化XML.

有任何功能性建议可以继续反馈OwO.

**Comment by RoslynMeow** [comment]
嗯, 其实最简单的就是让收发继承大类Client, 但那样我没有完成调试, 所以暂时不推送这个版本, 部分意见其实已经挺重合的了呢~ 233

**Comment by Executor-Cheng** [comment]
问题3: 基于时间复杂度考虑, 字典查值插值删值都是O(1), 现在的算法最差的情况可以是O(n), 如果你要坚持现有的设计的话, 可以考虑以下写法:
```csharp
while (true)
{
    if (SSMRequestList.TryDequeue(out JObject result))
    {
        if (result["syncId"].ToObject<int?>() == syncId)
        {
            return result;
        }
        SSMRequestList.Enqueue(result);
    }
    /*
    if (SSMRequestList.Count > 0)
    {
        if (SSMRequestList.First()["syncId"].ToObject<int?>() == syncId)
        {
            return SSMRequestList.Dequeue();
        }
        else
        {
            SSMRequestList.Enqueue(SSMRequestList.Dequeue());
        }
    }
    */
}
```
死循有个缺点就是如果发完报文, 好死不死的在收到响应前就被断开连接的话, 用户一直不重新连接, 方法就永远不会返回且一直消耗CPU
你可能需要自己考虑 `SendAndWaitResponse` 和 `Ws_MessageReceived` 之间的传递问题
问题4: 删不删 `async` / `await` 关键字都不会影响方法签名, 都是 `Task<bool> ConnectAsync()`

其它问题既然我俩设计观念不同的话, 我就不作回复了

**Comment by RoslynMeow** [comment]
1. 说实话我有想过这个`无响应断连`的情况
但我觉得"用户"如果非要这样那我的最好解决方案是 `抛出错误` 让线程`终止`. 从而避开这个逻辑.

2. 然后这个 `出队` 的方案吧... 我这个检查机制是TryDequeue的前体, 是个C#5的写法(有代码模板我一按就出来了) , 
具体可以查看dotnet库的Issues, 链接在这: https://github.com/dotnet/runtime/issues/15619, 
他的完整前体是 
```
public bool TryDequeue(out T result)
{
    if (_size == 0)
    {
        result = default(T);
        return false;
    }

    result = _array[_head];
    _array[_head] = default(T);
    MoveNext(ref _head);
    _size--;
    _version++;
    return true;
}
```
用也可以, 当时主要一是没怎么想就直接打出来了, 二是觉得没啥必要在这种缓冲区里面详细做个 trycatch, 
在最理想的标准情况下是队列只要入元素就直接被拿走解析了, 
而最差情况出现的条件是断连, 网络波动, 而这个操作可以通过直接检测网络问题抛错误 (观点1)

我还在想怎么样 "用户" 能获得最好的体验, 比如重连什么的....
不过我会考虑使用你的建议的, 因为.net内核是自己管理的, 我自己代码必然比不上内核优化.
感谢qwq. 如果还有问题可以继续讨论. 
或者你如果怕我看不到加我qq也可以的OvO

**Comment by RoslynMeow** [comment]
而且我这个框架是你拿去链接的,并不是什么代管的框架, `收到响应前就被断开连接` `必然是你自己的程序退出` 了, 
或者网络波动, 那就和上面的观点1暂时一致.
初版的设计是因为: 我个人感觉如果你发送了然后 `没有返回` 并不能算函数 `完成任务`, 
所以我会一直给他`卡在那`, 因为你不知道啥时候`就会返回`, 
在有重连机制以后我可能会考虑怎么修改他到更好的效率.

**Comment by RoslynMeow** [comment]
我做的更像是个工具包(大雾

**Comment by Executor-Cheng** [comment]
(｀・ω・´)企鹅就不加辽, 我一圈看下来大概就这些想法了

**Comment by Initial-heart-1** [comment]
围观，瑟瑟发抖

**Comment by RoslynMeow** [comment]
> (｀・ω・´)企鹅就不加辽, 我一圈看下来大概就这些想法了

感谢,感谢大佬指正意见, OvO
