### ISSUE TITLE
考虑完善开发文档

### ISSUE THREAD

**Issue by Initial-heart-1** [DavidSciMeow/MeowMiraiLib#2]
说真的，感觉确实有点丐了......
现在我还没搞明白 mah，回头搞明白了看源码看看能不能帮帮忙完善下文档（汗）
在这之前，大佬搞快点（

**Comment by Initial-heart-1** [comment]
对了，记得加上license......不然源码除了看啥都干不了😂

**Comment by RoslynMeow** [comment]
证书的话没想好, 但Nuget是AGPL-3.0-only.
当然欢迎整补充, 文档的话, 其实不用可以去写, 
微软内部一般用一个文档生成器 (NDoc或者Sandcastle),
我写那么多注释不是没原因的, 直接就能生成文档 awa

**Comment by Initial-heart-1** [comment]
> 证书的话没想好, 但Nuget是AGPL-3.0-only. 当然欢迎整补充, 文档的话, 其实不用可以去写, 微软内部一般用一个文档生成器 (NDoc或者Sandcastle), 我写那么多注释不是没原因的, 直接就能生成文档 awa

微软的文档，只能说能看，多了真不敢

**Comment by Initial-heart-1** [comment]
对了，尽可能少的使用绝对地址，否则不好维护
尽可能使用相对地址

**Comment by RoslynMeow** [comment]
你指的什么绝对地址..

**Comment by RoslynMeow** [comment]
最新版本已经更新,

**Comment by Initial-heart-1** [comment]
上帝这个令人血压拉满的文档

**Comment by Initial-heart-1** [comment]
您完全不会用md是吗

**Comment by Initial-heart-1** [comment]
好歹写成html啊

**Comment by RoslynMeow** [comment]
??就两句话还写啥HTML..都和原来API名一样...

**Comment by Initial-heart-1** [comment]
> ??就两句话还写啥HTML..都和原来API名一样...

你这个Readme看得我血压拉满

**Comment by RoslynMeow** [comment]
知道怎么接收就能用了啊.

**Comment by Initial-heart-1** [comment]
不是，哎，我直接改吧

**Comment by Initial-heart-1** [comment]
太难受了这

**Comment by RoslynMeow** [comment]
不是很理解你想表达什么..
可能这就是我前端设计不合格的原因吧.

**Comment by Initial-heart-1** [comment]
你这何止是前端设计不合格
你但凡排点版吧

**Comment by RoslynMeow** [comment]
我当时就只是粘贴一下就行了, 文档就这么多.. 也没必要写啥别的东西

**Comment by Initial-heart-1** [comment]
等有时间了我好好给你重编一下readme
等复试完吧

**Comment by Initial-heart-1** [comment]
这太离谱了

**Comment by RoslynMeow** [comment]
嗯, 就这些东西, 你随便改版就行

**Comment by Initial-heart-1** [comment]
~~看眼我写的[readme](https://github.com/AmiyaBot/Amiya-Bot/blob/master/README.md)，你就能理解为什么我蚌埠住了~~
我的，我的，我再干这事我自己爬

**Comment by RoslynMeow** [comment]
主要是我不写这玩意,没啥用...
要用的都去看代码内部注释了..
再不就是Ndoc生成的代码调试文档..

**Comment by Initial-heart-1** [comment]
能换个风格吗
上世纪的感觉来了

**Comment by d3ara1n** [comment]
> > ??就两句话还写啥HTML..都和原来API名一样...
> 
> 你这个Readme看得我血压拉满

README我发pr了，修复了格式报错，但内容一字没动

**Comment by Initial-heart-1** [comment]
了解了，GFM 太迷了

**Comment by Initial-heart-1** [comment]
> 了解了，GFM 太迷了

我是 Typora 写的，懒得 git 直接 web 复制粘贴了
