### ISSUE TITLE
[B]长时间运行后发送消息时抛出异常

### ISSUE THREAD

**Issue by LittleFish-233** [DavidSciMeow/MeowMiraiLib#5]
**问题描述**
短时间运行表现正常，但长时间（一天）运行后某次发送消息时会抛出异常 `Object reference not set to an instance of an object.` 详细信息贴在下面了。

**复现方案**
因为长时间运行才会出现，我也不清楚如何复现，
具体代码在： https://github.com/CnGal/CnGalWebSite/tree/master/CnGalWebSite/CnGalWebSite.RobotClient
我尝试描述一下我使用的方法：

1.监听群聊消息
```csharp

//Program.cs
c.OnGroupMessageReceive += async (s, e) =>
{
    try
    {
        await clientX.ReplyFromGroupAsync(s, e,);
    }
    catch (Exception ex)
    {
        OutputHelper.PressError(ex);
    }

};

//ClientX.cs
public async Task ReplyFromGroupAsync(GroupMessageSender s, Message[] e, RobotReplyRange range)
{
     var message = e.MGetPlainString();
    var sendto = s.group.id;
          
     //尝试找出所有匹配的回复
    var reply = _messageX.GetAutoReply(message,range);

    if (reply == null)
    {
         return;
    }

    var result = new Message[] { };
    //转换纯文本回复为Message[]
    result = await _messageX.ProcMessageAsync(reply.Value, message, reply.Key, s.id, s.memberName);

    if (result != null)
    {
        var j = await new GroupMessage(sendto, result).SendAsync(MiraiClient);
        Console.WriteLine(j);
    }
}
```

2.定时消息
```csharp

//Program.cs
System.Timers.Timer t = new(1000 * 60); //每一分钟查看一次
t.Start(); //启动计时器
t.Elapsed += async (s, e) =>
{
    //获取定时消息
    var message = eventX.GetCurrentTimeEvent();
    if (string.IsNullOrWhiteSpace(message) == false)
    {
        //转换纯文本消息为Message[]
        var result = await messageX.ProcMessageAsync(message, "", null, 0, null);

        if (result != null)
        {
                var j = await new GroupMessage(groupId, result).SendAsync(c);
                Console.WriteLine(j);
        }
    }
};

```

**正确的反馈**

**屏幕截图(错误截图,异常截图)**

下面这几张图不在同一时间，还请见谅

因为没有捕获异常而退出程序的提示，之前尝试过捕获但是没有效果

![AL{7QRVPXW1CFZ29ARMJS S](https://user-images.githubusercontent.com/53342258/174479058-8c3f192a-9aa1-4b49-918b-bd1b164f9eca.jpg)

调用堆栈

![K$~O`H1_}27(MSXC6YZV3P](https://user-images.githubusercontent.com/53342258/174479049-ce3886cb-2001-44aa-b18d-de1a9808f9c5.png)

程序异常前的输出

![image](https://user-images.githubusercontent.com/53342258/174479030-1c844d02-fba9-4ce5-89c3-ced445f57741.png)

**你的版本**
操作系统:Windows Server 2012
SDK版本:
.Net 6.0.5 
MeowMiraiLib 6.0.1

**其他信息**
希望大佬能指出使用方式哪里有错误，或者用其他方式可以实现稳定运行，十分感谢

如果还需要提供其他信息，我也会补充

电子邮箱：LittleFishTenyears@outlook.com

**Comment by RoslynMeow** [comment]
在我看来是发送端的时候端断链了.我尝试更新一版不会自动重连的.
有些时候这个重连的机制不太一样, 
我在linux上能捕获到的是实例显示断连, 
但我也在windows上曾经捕获过npe (null pointer exception) .

----
当时的原因是这个Client有时候断线被GC回收了, 你发送的时候他就npe.  
也有时候GC没回收, 那就会进我的重连流程.    

----
我没改是因为当时`"我"还没有觉得这个能出现什么大问题`, 
因为我的机器(内网)五次以内总是能重连上的,
目前我看你的记录就能想到这些, 我正在尝试一个修改, 
另外如果可能的话最好说一下你的`业务流程`
这几个代码我看不出调用情况和先后顺序,在逻辑上看他们可能是异步的.
不过你说得对,我会更新一个守护链的..(我也正在做)

我会在本页更新一下对你有用的一些东西....感谢反馈呢喵w

**Comment by RoslynMeow** [comment]
![image](https://user-images.githubusercontent.com/31565570/174571005-ae9f14d0-4073-4a23-88b9-d25a589eb5ff.png)
![image](https://user-images.githubusercontent.com/31565570/174571121-fd2d2611-e6f6-41d0-8548-81ab522147d4.png)

有些时候确实会遇到这种就是非正常关闭的...因为我没用 
```
ws?.Send();
```

**Comment by RoslynMeow** [comment]
如果可能的话最好看看是发送的问题还是内部调用的问题
```
//因为你的堆栈最后一个地方是 SendAndWaitResponse() 函数, 
//我能想到的就是ws.Send()出现的npe.
```

**Comment by LittleFish-233** [comment]
> 另外如果可能的话最好说一下你的业务流程
这几个代码我看不出调用情况和先后顺序,在逻辑上看他们可能是异步的.

`定时发送消息`和`回复消息`确实是异步的，我尝试贴一下流程图（虽然可能不太直观

![image](https://user-images.githubusercontent.com/53342258/174572543-90f2761a-fc06-44c9-b9ab-8f1e6a3a2f0b.png)

> 如果可能的话最好看看是发送的问题还是内部调用的问题

好的，我这几天看一下

十分感谢~\(≧▽≦)/~

**Comment by RoslynMeow** [comment]
哦你这个,我建议分开实例,我给你看看我的燐燐怎么做的...
哦对了,其实如果可以你可以分开多线程, 一个链接对象可以不限制链接次数, 他们会自己管理

**Comment by RoslynMeow** [comment]
而且,最重要的其实我更建议使用我写的扩展 
```csharp
var r = new Message[] { new Plain($"....") }.SendToFriend(s.id, client);
```

**Comment by RoslynMeow** [comment]
发图也有发图的语法糖
```csharp
new Message[] { new Image(base64: base64str) }.SendToFriend(s.id, client);
```

**Comment by LittleFish-233** [comment]
> 哦对了,其实如果可以你可以分开多线程, 一个链接对象可以不限制链接次数, 他们会自己管理
> 而且,最重要的其实我更建议使用我写的扩展

好的，我试着修改一下

**Comment by RoslynMeow** [comment]
我一会Push一个更改守护链的,试试能不能星,你是打日志的哈
![image](https://user-images.githubusercontent.com/31565570/174574216-178c0f2f-7470-4176-adc1-c11dce5b9598.png)

**Comment by LittleFish-233** [comment]
嗯，会记录日志的

**Comment by RoslynMeow** [comment]
我曾经也考虑过,一旦`发送信息的时候`断连,
但我觉得可能性太小了,我就没改,
我单独给你一版打包好的nuget,给你发QQ还是邮箱还是什么,

**Comment by LittleFish-233** [comment]
发邮箱就行，LittleFishTeayears@outlook.com
辛苦了o((>ω< ))o

**Comment by RoslynMeow** [comment]
你有啥想加的功能啥的么,我到时候可以给你写进去

**Comment by LittleFish-233** [comment]
已经写得很完善了，感觉目前功能够用，我没想到什么需要加的╮(╯-╰)╭

**Comment by RoslynMeow** [comment]
我看了看,我尝试用网络波动,能复现NPE...不知道是不是一个...我直接推给nuget吧,我一会通知你在VS里面更新.

**Comment by RoslynMeow** [comment]
![image](https://user-images.githubusercontent.com/31565570/174575771-82f318dc-0796-471d-a8e1-94264c1c59f2.png)
如果你的日志出现 `[MeowMiraiLib-SocketWatchdog * Sending with NetFlaws]` 那应该就是我判断对了, 到时候可以看看

**Comment by LittleFish-233** [comment]
好的

**Comment by RoslynMeow** [comment]
action已经publish完了
![image](https://user-images.githubusercontent.com/31565570/174576191-ef7b4647-7972-44ed-ae23-f316a5a02efd.png)

**Comment by RoslynMeow** [comment]
等等nuget index完了应该就OK了.

**Comment by RoslynMeow** [comment]
我仍然建议如果可能的话可以分多线程分别连不同的实例,
你可以对一个URL创建多个实例(只要你的服务器端口允许)
这样更方便排错.

**Comment by RoslynMeow** [comment]
但是如果这个应用整体打包的话你这样也可以,
我只是说一下可以整多个实例(大雾)

**Comment by RoslynMeow** [comment]
说实话我都没想过我瞎写的玩意能有人用(

**Comment by RoslynMeow** [comment]
应该index好了(去试试吧,我先把这个问题一直开着.有进展回复就行

**Comment by LittleFish-233** [comment]
我本地调试了一下，npe应该是Queue的出队数据造成的，不是WS，试着修改了一下代码 #6

**Comment by RoslynMeow** [comment]
#6 感谢处理,一会我会发一版本新的7.0.0

**Comment by RoslynMeow** [comment]
已经注明了你的贡献,感谢关注这个小项目.感谢你为了我一个无法复现操作的辛勤付出.

**Comment by LittleFish-233** [comment]
只是做了一些微小的工作，也希望`MeowMiraiLib`能越做越好(ง •_•)ง
