### ISSUE TITLE
需求：支持商城表情构造和发送

### ISSUE THREAD

**Issue by LittleFish-233** [DavidSciMeow/MeowMiraiLib#7]
希望支持商城表情构造和发送

**Comment by RoslynMeow** [comment]
我看了下, 应该是不支持构造发送, 我看了一下 MarketFace 构造说明, 我会支持这个类型, 但是因为我是基于HTTPAPI, 所以确实没法发送
https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/MessageType.md#marketface

**Comment by RoslynMeow** [comment]
类内支持实例化 MarketFace, 你可以试试转发

**Comment by RoslynMeow** [comment]
@Message.cs 的 545 行
```
    /// <summary>
    /// 商城表情
    /// </summary>
    public sealed class MarketFace : Message
    {
        /// <summary>
        /// 商城表情唯一标识
        /// </summary>
        public int id;
        /// <summary>
        /// 表情显示名称
        /// </summary>
        public string name;
        /// <summary>
        /// 构造一个商城表情
        /// <para>目前商城表情仅支持接收和转发,不支持构造发送</para>
        /// </summary>
        /// <param name="id">商城表情唯一标识</param>
        /// <param name="name">表情显示名称</param>
        public MarketFace(int id, string name)
        {
            this.id = id;
            this.name = name;
        }
    }
```

**Comment by RoslynMeow** [comment]
有别的问题随时追问, 我最近在测试识别逻辑, 实现和某个用户的多对话交流逻辑. 不知道你们需不需要.

**Comment by LittleFish-233** [comment]
> 类内支持实例化 MarketFace, 你可以试试转发

如何进行转发呢，是其他用户发送表情之后再转发吗？

> 我最近在测试识别逻辑, 实现和某个用户的多对话交流逻辑. 不知道你们需不需要.

我们也计划做上下文交流，但目前还在搁置中

**Comment by RoslynMeow** [comment]
他的底是不支持的, 主要是没法`看出来是什么`, 如果用户发了表情以后, 
你可以提取出来然后试试直接发送.
你可以试试用如下的试试他会不会复读你的商城表情.
```
r.OnFriendMessageReceive += (s, e) =>
{
    foreach (var i in e)
    {
        if (i is MarketFace)
        {
            var k = i as MarketFace;
            new FriendMessage(s.id, new[] { k }).Send(r);
        }
    }
};
```

**Comment by RoslynMeow** [comment]
我没试过商城表情,据说跟你的QQ`是否有`这个商城表情的`订阅`有关..我不是很理解而且调试也比较麻烦.

**Comment by RoslynMeow** [comment]
我也不知道这个name会不会随着用户和时间变换,还是别的什么,如果详细调试你可以试试这么写
```
rinko.OnFriendMessageReceive += (s, e) =>
{
    foreach (var i in e)
    {
        if (i is MarketFace)
        {
            var k = i as MarketFace;
            new FriendMessage(s.id, new[] { new Plain($"{k.id} {k.name} {k.type} \n 复读如下:") }).Send(rinko);
            new FriendMessage(s.id, new[] { k }).Send(rinko);
        }
    }
};
```

**Comment by RoslynMeow** [comment]
如果能复读成功的话, 那你可以构造一个表情, 加上他的name和id试试能发不能.

**Comment by RoslynMeow** [comment]
因为这个解析不是我做的, 是MiraiHttpAPI解析好, 我把Json对位换成C#的类而已, 所以HTTPAPI解析成什么, 实际上我是没法控制的.
如果你只发送固定的几个, 那你可以找找规律, 如果要是动态添加和发送, 那你只能期待HTTPAPI先支持, 然后我马上第一时间增加功能.

**Comment by RoslynMeow** [comment]
我的评价方案是保存商城表情你要的变成图啥的,直接发图(唯一我想到的替代方案)

**Comment by RoslynMeow** [comment]
然后最后提一嘴, 上下文交互我目前准备写成lambda注入式的, 但我不太看好效率, 我还在优化, 不知道你们有啥具体想法.

**Comment by LittleFish-233** [comment]
非常感谢，我也去 `mirai-api-http` 那边提个Issue，上下文交互还没有什么具体想法，搁置中o((>ω< ))o

**Comment by RoslynMeow** [comment]
另, 更新了Wiki, 欢迎提意见

**Comment by RoslynMeow** [comment]
> 非常感谢，我也去 `mirai-api-http` 那边提个Issue，上下文交互还没有什么具体想法，搁置中o((>ω< ))o

上下文端已经更新, 欢迎给出意见.
